language: cpp

compiler:
    - gcc

before_install:
    - sudo apt-get update
    - sudo apt-get install python3

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - pip install httplib2

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-4.8
    - g++-4.8
